### ISSUE TITLE
rethinking these data structures

### ISSUE THREAD

**Issue by mr-c** [h3abionet/h3abionet16S#9]
While the `ReadPair` data type defines only two fields, the `completeWorkflow.cwl` currently also requires the `sample_id` field

Upon reflection I think that it would be best to make that extra fields explicit so I'd like to propose two small changes to the custom types: 

1) rename `FilePair` to `sequence_pair` for better readability
2) new type, `labeled_sequence_pair` that include the mandatory `sample_id`

```
types:
  - name: sequence_pair
    type: record
    fields:
      - name: forward
        type: File
      - name: reverse
        type: File
  - name: labeled_sequence_pair
    type: record
    fields:
      - name: sample_id
        type: string
      - name: sequences
        type: FilePair
```
     
If the other metadata fields seen in https://github.com/h3abionet/h3abionet16S/blob/master/example/input.yml become mandatory then they can also be added to `labeled_sequence_pair` to make the requirement explicit

Thoughts?
